try{
  x();
} catch (error) {
  console.log(error);
}
